const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
if (!process.env.PLAYWRIGHT_BROWSERS_PATH && fs.existsSync('.tools/browsers')) process.env.PLAYWRIGHT_BROWSERS_PATH = path.resolve('.tools/browsers');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const types = { '.html': 'text/html', '.css': 'text/css', '.js': 'application/javascript', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.woff2': 'font/woff2' };
const server = http.createServer((req, res) => {
  const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
  const filename = path.resolve(root, '.' + (pathname === '/' ? '/index.html' : pathname));
  if (!filename.startsWith(root + path.sep)) { res.writeHead(403); res.end(); return; }
  fs.readFile(filename, (error, data) => {
    res.writeHead(error ? 404 : 200, { 'Content-Type': types[path.extname(filename)] || 'text/plain' });
    res.end(error ? 'Not found' : data);
  });
});

(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ headless: true });
  const errors = [];
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  // Peta pihak ketiga dikecualikan dari pengujian aset lokal.
  await context.route(/https:\/\/(maps\.google\.com|www\.google\.com)/, route => route.fulfill({ body: '<p>Google Maps — aperçu externe</p>', contentType: 'text/html' }));
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.url().startsWith(origin) && response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  try {
    await page.goto(origin);
    await page.waitForFunction(() => window.Alpine && document.querySelector('body')._x_dataStack);
    assert.equal(await page.locator('h1').count(), 1);
    const title = await page.title();
    assert(title.length >= 50 && title.length <= 60, `Title length: ${title.length}`);
    assert.equal(await page.locator('#job-grid article').count(), 15);
    assert.equal(await page.locator('#job-grid article:visible').count(), 1);
    assert.equal(await page.locator('.filter-chip').count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Bidang kerja sebelumnya' }).count(), 1);
    assert.equal(await page.getByRole('button', { name: 'Bidang kerja berikutnya' }).count(), 1);
    assert.equal(await page.locator('#field option').count(), 16);
    assert.equal(await page.locator('img:not([loading="lazy"])').count(), 2);
    assert.equal(await page.locator('.hero-background').first().getAttribute('loading'), 'eager');
    assert.equal(await page.locator('img:not([alt]), img:not([width]), img:not([height])').count(), 0);
    assert.equal(await page.locator('script[type="application/ld+json"]').evaluate(el => JSON.parse(el.textContent)['@type']), 'Organization');
    const brokenAnchors = await page.locator('a[href^="#"]').evaluateAll(links => links.filter(link => !document.getElementById(link.hash.slice(1))).map(link => link.hash));
    assert.deepEqual(brokenAnchors, []);
    const jobSlides = page.locator('#job-grid article');
    const jobImages = [
      'sector-kaigo.webp', 'sector-pertanian.webp', 'sector-perikanan.webp',
      'sector-konstruksi.webp', 'sector-pengolahan-makanan.webp', 'sector-restoran.webp',
      'sector-manufaktur-mesin.webp', 'sector-elektronik.webp', 'sector-pembuatan-kapal.webp',
      'sector-pembersihan.webp', 'sector-suku-cadang.webp', 'sector-penerbangan.webp',
      'sector-perhotelan.webp', 'sector-pengecatan.webp', 'sector-pengelasan.webp'
    ];
    const nextJob = page.getByRole('button', { name: 'Bidang kerja berikutnya' });
    const previousJob = page.getByRole('button', { name: 'Bidang kerja sebelumnya' });
    for (let index = 0; index < jobImages.length; index++) {
      assert.equal(await page.locator('#job-grid article:visible').count(), 1);
      const photo = await jobSlides.nth(index).locator('.job-icon').evaluate(el => getComputedStyle(el).backgroundImage);
      assert(photo.includes(jobImages[index]), `Photo for slide ${index + 1}: ${photo}`);
      if (index < jobImages.length - 1) await nextJob.click();
    }
    await nextJob.click();
    assert.equal(await jobSlides.nth(0).isVisible(), true, 'Next wraps to first job');
    await previousJob.click();
    assert.equal(await jobSlides.nth(14).isVisible(), true, 'Previous wraps to last job');
    await nextJob.click();
    await page.keyboard.press('ArrowRight');
    assert.equal(await jobSlides.nth(1).isVisible(), true, 'Keyboard advances the jobs slideshow');
    await page.keyboard.press('ArrowLeft');
    assert.equal(await jobSlides.nth(0).isVisible(), true, 'Keyboard reverses the jobs slideshow');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.locator('#job-grid article:visible').count(), 1);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('link', { name: 'Konsultasikan bidang Keperawatan (Kaigo)', exact: true }).click();
    await page.locator('input[name="currentLocation"][value="Indonesia"]').check();
    await page.getByRole('button', { name: 'Lanjutkan', exact: true }).click();
    assert.equal(await page.locator('#field').inputValue(), 'Keperawatan (Kaigo)');
    let posts = 0;
    page.on('request', request => { if (request.method() === 'POST') posts++; });
    const nextStep = page.getByRole('button', { name: 'Selanjutnya', exact: true });
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="0"]').isVisible(), 'Required email keeps the applicant on the first step');
    assert.equal(await page.locator(':focus').getAttribute('id'), 'email');
    await page.locator('#email').fill('budi@example.com');
    await page.locator('input[name="jobOrderConsultation"][value="Ya"]').check();
    await page.locator('#romaji').fill('Budi Santoso');
    await page.locator('#katakana').fill('ブディ サントソ');
    await page.locator('#gender').selectOption('Laki-laki');
    await page.locator('#birthPlace').fill('Jakarta');
    await page.locator('#birthDate').fill('2000-01-01');
    await page.locator('#identityAddress').fill('Jl. Contoh No. 1, Jakarta');
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="1"]').isVisible());
    await page.locator('input[name="maritalStatus"][value="Belum menikah"]').check();
    await page.locator('#height').fill('170');
    await page.locator('#weight').fill('65');
    await page.locator('#motherName').fill('Siti');
    await page.locator('#fatherName').fill('Bambang');
    await page.locator('#guardianPhone').fill('081234567890');
    await page.locator('#guardianAddress').fill('Jl. Wali No. 2, Jakarta');
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="2"]').isVisible());
    await page.locator('input[name="diagnosedDisease"][value="Ya"]').check();
    await page.locator('#diseaseName').fill('Contoh penyakit');
    await page.locator('input[name="diagnosedDisease"][value="Tidak"]').check();
    await page.locator('#diseaseName').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#diseaseName').inputValue(), '', 'Hidden health answers are cleared');
    await page.locator('input[name="willingMcu"][value="Ya"]').check();
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="3"]').isVisible());
    await page.locator('input[name="education"][value="SMA/SMK"]').check();
    await page.locator('#school').fill('SMA Negeri 1');
    await page.locator('#major').fill('IPA');
    await page.locator('#latestGrade').fill('85');
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="4"]').isVisible());
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="5"]').isVisible());
    await page.locator('input[name="workedInJapan"][value="Tidak"]').check();
    await page.locator('input[name="overstay"]').first().waitFor({ state: 'visible' });
    assert(await page.locator('input[name="overstay"]').first().isVisible());
    await page.locator('input[name="workedInJapan"][value="Ya"]').check();
    await page.locator('#visaStatus').waitFor({ state: 'visible' });
    assert(await page.locator('#visaStatus').isVisible(), 'Yes branch exposes Japan employment details');
    await page.locator('input[name="workedInJapan"][value="Tidak"]').check();
    await page.locator('input[name="visitedJapan"][value="Tidak"]').check();
    await page.locator('input[name="overstay"][value="Tidak"]').check();
    await page.locator('input[name="deported"][value="Tidak"]').check();
    await page.locator('input[name="visaRejected"][value="Tidak"]').check();
    await page.locator('input[name="overstay"]').first().waitFor({ state: 'visible' });
    assert.equal(await page.locator('#visaStatus').inputValue(), '', 'Hidden Japan work answers are cleared');
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="6"]').isVisible());
    const oversizedPdf = { name: 'cv.pdf', mimeType: 'application/pdf', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) };
    await page.locator('#cv').setInputFiles(oversizedPdf);
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="6"]').isVisible(), 'Files larger than 10 MB are rejected');
    await page.getByText('Ukuran file maksimal 10 MB.', { exact: true }).waitFor({ state: 'visible' });
    const samplePdf = { name: 'dokumen.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.7') };
    await page.locator('#cv').setInputFiles({ ...samplePdf, name: 'cv.pdf' });
    await page.locator('#identityCard').setInputFiles({ ...samplePdf, name: 'ktp.pdf' });
    await page.locator('#familyCard').setInputFiles({ ...samplePdf, name: 'kk.pdf' });
    await page.locator('#diploma').setInputFiles({ ...samplePdf, name: 'ijazah.pdf' });
    await nextStep.click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="7"]').isVisible());
    await page.locator('#declaration').check();
    await page.getByRole('button', { name: 'Kembali', exact: true }).click();
    assert(await page.locator('[data-form-route="Indonesia"][data-form-step="6"]').isVisible());
    assert.equal(await page.locator('#cv').evaluate(input => input.files[0]?.name), 'cv.pdf');
    await nextStep.click();
    await page.getByRole('button', { name: 'Kirim Formulir', exact: true }).click();
    await page.getByText('Formulir demo: data dan dokumen belum dikirim atau disimpan.', { exact: true }).waitFor();
    assert.equal(posts, 0, 'Demo must not submit personal data');
    await page.evaluate(() => { window.NIPPON_ACE_CONFIG = { webhookUrl: 'https://script.google.com/macros/s/LOCAL_TEST/exec' }; });
    await page.getByRole('button', { name: 'Kirim Formulir', exact: true }).click();
    await page.getByText('Endpoint saat ini belum mendukung formulir pendaftaran dan unggahan dokumen.', { exact: false }).waitFor();
    assert.equal(posts, 0, 'The legacy consultation endpoint must not receive applicant documents');
    await page.getByRole('button', { name: 'Testimoni berikutnya' }).click();
    await page.getByText('Siti Rahma', { exact: true }).waitFor({ state: 'visible' });
    assert(await page.getByText('Siti Rahma', { exact: true }).isVisible());
    await page.getByRole('button', { name: 'Testimoni sebelumnya' }).click();
    await page.getByText('Andi Saputra', { exact: true }).waitFor({ state: 'visible' });
    assert(await page.getByText('Andi Saputra', { exact: true }).isVisible());
    await page.reload();
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.evaluate(() => document.fonts.ready);
    await page.locator('.hero-background').first().evaluate(image => image.decode());
    fs.mkdirSync(path.join(root, 'test-results'), { recursive: true });
    await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
    for (const width of [320, 390, 768, 1024, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}px`);
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Buka atau tutup navigasi' }).click();
    await page.locator('#mobile-nav').waitFor({ state: 'visible' });
    assert(await page.locator('#mobile-nav').isVisible());
    await page.keyboard.press('Escape');
    await page.locator('#mobile-nav').waitFor({ state: 'hidden' });
    assert(!(await page.locator('#mobile-nav').isVisible()));
    await page.getByRole('button', { name: 'Buka atau tutup navigasi' }).click();
    await page.locator('#mobile-nav').getByRole('link', { name: 'Bidang Kerja' }).click();
    await page.locator('#mobile-nav').waitFor({ state: 'hidden' });
    assert(!(await page.locator('#mobile-nav').isVisible()));
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
    const noJS = await browser.newContext({ javaScriptEnabled: false });
    await noJS.route(/https:\/\/maps\.google\.com/, route => route.fulfill({ body: '' }));
    const staticPage = await noJS.newPage();
    await staticPage.goto(origin);
    assert.equal(await staticPage.locator('#job-grid article:visible').count(), 15);
    assert(await staticPage.locator('h1').isVisible());
    assert.equal((await staticPage.locator('.hero-title .is-active').textContent()).replace(/\s+/g, ' ').trim(), 'Raih Karir Impianmu di Jepang Bersama Kami');
    assert.equal(await staticPage.locator('.hero-controls').isVisible(), false);
    await noJS.close();
    // Hero uses independent state from the testimonial carousel.
    const heroPage = await context.newPage();
    heroPage.on('pageerror', error => errors.push(error.message));
    await heroPage.clock.install();
    await heroPage.emulateMedia({ reducedMotion: 'no-preference' });
    await heroPage.goto(origin);
    await heroPage.waitForFunction(() => document.querySelector('#beranda')._x_dataStack?.[0].timer);
    const heroState = () => heroPage.locator('#beranda').evaluate(el => el._x_dataStack[0].current);
    assert.equal(await heroState(), 0);
    await heroPage.clock.fastForward(4500);
    assert.equal(await heroPage.locator('.hero-background.is-active').evaluate(el => getComputedStyle(el).animationDuration), '4.5s');
    assert.equal(await heroState(), 1, 'Autoplay advances after 4.5 seconds');
    assert.equal((await heroPage.locator('.hero-title .is-active').textContent()).replace(/\s+/g, ' ').trim(), 'Bimbingan Karier Sesuai Minat dan Pengalamanmu');
    assert.equal(await heroPage.locator('.hero-background.is-active').getAttribute('src'), 'assets/images/hero-agriculture.webp');
    await heroPage.getByRole('button', { name: 'Slide hero berikutnya' }).click();
    assert.equal(await heroState(), 2);
    await heroPage.getByRole('button', { name: 'Slide hero berikutnya' }).click();
    assert.equal(await heroState(), 0, 'Next wraps to first slide');
    await heroPage.getByRole('button', { name: 'Slide hero sebelumnya' }).click();
    assert.equal(await heroState(), 2, 'Previous wraps to last slide');
    await heroPage.getByRole('button', { name: 'Slide 1: Gunung Fuji' }).click();
    await heroPage.clock.fastForward(10000);
    assert.equal(await heroState(), 0, 'Focus and hover suspend autoplay');
    await heroPage.keyboard.press('ArrowRight');
    assert.equal(await heroState(), 1, 'Keyboard controls hero');
    await heroPage.getByRole('button', { name: 'Jeda otomatis hero' }).click();
    await heroPage.locator('.hero-control:focus').evaluate(el => el.blur());
    await heroPage.mouse.move(0, 0);
    await heroPage.clock.fastForward(10000);
    assert.equal(await heroState(), 1, 'Explicit pause persists after leaving hero');
    await heroPage.getByRole('button', { name: 'Putar otomatis hero' }).click();
    await heroPage.locator('.hero-control:focus').evaluate(el => el.blur());
    await heroPage.mouse.move(0, 0);
    await heroPage.waitForFunction(() => document.querySelector('#beranda')._x_dataStack[0].timer);
    await heroPage.clock.fastForward(4500);
    assert.equal(await heroState(), 2, 'Playback resumes');
    await heroPage.emulateMedia({ reducedMotion: 'reduce' });
    await heroPage.waitForFunction(() => !document.querySelector('#beranda')._x_dataStack[0].timer);
    await heroPage.clock.fastForward(10000);
    assert.equal(await heroState(), 2, 'Reduced motion disables autoplay');
    await heroPage.locator('.hero-background').evaluateAll(images => Promise.all(images.map(image => image.decode())));
    for (const width of [320, 390, 768, 1024, 1440]) {
      await heroPage.setViewportSize({ width, height: 900 });
      for (let index = 0; index < 3; index++) {
        await heroPage.locator('.hero-dot').nth(index).click();
        assert(await heroPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Hero overflow at ${width}px, slide ${index + 1}`);
        assert(await heroPage.getByRole('link', { name: 'Daftar Sekarang', exact: true }).isVisible());
        assert(await heroPage.getByRole('link', { name: 'Jelajahi Lowongan', exact: true }).isVisible());
      }
    }
    await heroPage.close();
    assert.deepEqual(errors, []);
    console.log('PASS: SEO basics, 15-slide jobs carousel, seven-step applicant form, conditional Japan history, PDF limit, no-send demo, testimonials carousel, mobile navigation, 5 viewport widths, no-JS content, local assets and JS errors.');
    console.log('Screenshots: test-results/desktop.png, test-results/mobile.png');
  } finally { await context.close(); await browser.close(); server.close(); }
})().catch(error => { console.error(error); server.close(); process.exitCode = 1; });
